#!/bin/bash
# =============================================================================
# Script de validación de inserciones iniciales - ERP Core
# Verifica que los datos de prueba sean consistentes con el esquema
# =============================================================================

print_message() {
    local color=$1
    local message=$2
    echo -e "${color}[$(date '+%H:%M:%S')] ${message}\033[0m"
}

print_success() { print_message "\033[0;32m" "✅ $1"; }
print_info() { print_message "\033[0;34m" "ℹ️  $1"; }
print_warning() { print_message "\033[1;33m" "⚠️  $1"; }
print_error() { print_message "\033[0;31m" "❌ $1"; }

echo "🔍 Validando inserciones iniciales de desarrollo..."
echo "==============================================================================="

# Verificar que los contenedores estén corriendo
if ! docker compose ps | grep -q "Up"; then
    print_error "Los contenedores no están corriendo. Ejecuta: ./start-services.sh"
    exit 1
fi

print_info "Analizando archivo 02-insert.sql..."

# Problemas identificados
echo ""
print_warning "🚨 PROBLEMAS IDENTIFICADOS EN EL ARCHIVO 02-INSERT.SQL:"
echo ""

echo "1. ❌ ESQUEMAS FALTANTES:"
echo "   - Las tablas deben usar el esquema 'core'"
echo "   - Ejemplo: INSERT INTO core.tipo_contacto ..."
echo ""

echo "2. ❌ NOMBRES DE COLUMNAS INCORRECTOS:"
echo "   - tabla 'permiso': usa 'nombre' pero debe ser 'per_nombre'"
echo "   - tabla 'permiso': usa 'descripcion' pero debe ser 'per_desc'" 
echo "   - tabla 'permiso': usa 'codigo' pero debe ser 'per_cod'"
echo "   - tabla 'permiso': usa 'activo' pero debe ser 'per_activo'"
echo ""

echo "3. ❌ NOMBRE DE COLUMNA EN MÓDULO:"
echo "   - tabla 'modulo': usa 'activo' pero debe ser '\"Estado de modulo\"'"
echo ""

echo "4. ⚠️  CLAVES PRIMARIAS AUTO-INCREMENTABLES:"
echo "   - No especificar IDs en tablas con GENERATED BY DEFAULT AS IDENTITY"
echo "   - Excepto cuando necesites un ID específico"
echo ""

echo "==============================================================================="
print_info "Creando archivo corregido: 02-insert-corrected.sql"

# Crear archivo corregido
cat > init-db/02-insert-corrected.sql << 'EOF'
-- =============================================================================
-- Inserciones iniciales para desarrollo - ERP Core (CORREGIDO)
-- =============================================================================

-- NOTA: Usar el esquema core en todas las inserciones

-- Insertar tipos de contacto
INSERT INTO core.tipo_contacto (nombre, descripcion) VALUES 
    ('Persona', 'Contacto personal'),
    ('Empresa', 'Contacto empresarial'),
    ('Proveedor', 'Contacto de proveedor'),
    ('Cliente', 'Contacto de cliente');

-- Insertar contactos de prueba
INSERT INTO core.contacto (nombre, direccion, celular, correo, redes_sociales, url, imagen_base64, tipo_contacto_id)
VALUES 
    ('Juan Pérez', 'Av. Principal 123', '+56987654321', 'juan.perez@email.com', '@juan_perez', 'https://juan.dev', NULL, 1),
    ('María González', 'Calle Comercio 456', '+56912345678', 'maria@empresa.com', '@maria_ceo', 'https://empresa.com', NULL, 2),
    ('Proveedor XYZ Ltda.', 'Industrial 789', '+56998877665', 'contacto@proveedorxyz.com', '@proveedorxyz', 'https://proveedorxyz.com', NULL, 3);

-- Insertar organizaciones
INSERT INTO core.organizacion (razon_social, rut, dv, giro, logo_base64, contacto_id)
VALUES 
    ('Tech Solutions SpA', '76543210', '5', 'Desarrollo de software', NULL, 2),
    ('Proveedor XYZ Ltda.', '87654321', '3', 'Suministros industriales', NULL, 3);

-- Insertar cuentas bancarias
INSERT INTO core.cuenta_bancaria (nombre_titular, banco, numero, correo_contacto, rut_titular, organizacion_id)
VALUES 
    ('Tech Solutions SpA', 'Banco Estado', '12345678901', 'finanzas@techsolutions.com', '76543210-5', 1),
    ('Proveedor XYZ Ltda.', 'Banco Santander', '98765432109', 'admin@proveedorxyz.com', '87654321-3', 2);

-- Insertar sistemas
INSERT INTO core.sistema (nombre, descripcion, activo)
VALUES 
    ('ERP Core', 'Sistema de gestión empresarial principal', true),
    ('CRM', 'Sistema de gestión de clientes', true),
    ('Inventario', 'Sistema de gestión de inventario', false);

-- Insertar módulos
INSERT INTO core.modulo (nombre, descripcion, "Estado de modulo", sistema_id)
VALUES 
    ('Gestión de Usuarios', 'Administración de usuarios y accesos', true, 1),
    ('Gestión de Contactos', 'Administración de contactos', true, 1),
    ('Gestión de Organizaciones', 'Administración de organizaciones', true, 1),
    ('Reportes', 'Generación de reportes', false, 1),
    ('Ventas', 'Gestión de ventas', true, 2);

-- Insertar relaciones organización-sistema
INSERT INTO core.organizacion_sistema (organizacion_id, sistema_id) VALUES 
    (1, 1),  -- Tech Solutions usa ERP Core
    (1, 2),  -- Tech Solutions usa CRM
    (2, 1);  -- Proveedor XYZ usa ERP Core

-- Insertar roles
INSERT INTO core.rol (nombre, descripcion) VALUES 
    ('Super Administrador', 'Acceso completo a todo el sistema'),
    ('Administrador', 'Acceso administrativo limitado'),
    ('Usuario Estándar', 'Acceso básico de usuario'),
    ('Supervisor', 'Supervisión de operaciones'),
    ('Solo Lectura', 'Solo puede consultar información');

-- Insertar permisos (USAR NOMBRES DE COLUMNA CORRECTOS)
INSERT INTO core.permiso (per_nombre, per_desc, per_cod, per_activo) VALUES 
    ('Ver Usuarios', 'Puede visualizar usuarios', 'USR_VIEW', true),
    ('Crear Usuarios', 'Puede crear nuevos usuarios', 'USR_CREATE', true),
    ('Editar Usuarios', 'Puede modificar usuarios existentes', 'USR_EDIT', true),
    ('Eliminar Usuarios', 'Puede eliminar usuarios', 'USR_DELETE', true),
    ('Ver Contactos', 'Puede visualizar contactos', 'CNT_VIEW', true),
    ('Crear Contactos', 'Puede crear nuevos contactos', 'CNT_CREATE', true),
    ('Editar Contactos', 'Puede modificar contactos', 'CNT_EDIT', true),
    ('Eliminar Contactos', 'Puede eliminar contactos', 'CNT_DELETE', false),
    ('Ver Organizaciones', 'Puede visualizar organizaciones', 'ORG_VIEW', true),
    ('Administrar Sistema', 'Puede administrar configuraciones del sistema', 'SYS_ADMIN', true);

-- Insertar relaciones módulo-permiso
INSERT INTO core.modulo_permiso (modulo_id, permiso_id) VALUES 
    -- Gestión de Usuarios (módulo 1)
    (1, 1), (1, 2), (1, 3), (1, 4),
    -- Gestión de Contactos (módulo 2) 
    (2, 5), (2, 6), (2, 7), (2, 8),
    -- Gestión de Organizaciones (módulo 3)
    (3, 9),
    -- Reportes (módulo 4) - solo lectura
    (4, 1), (4, 5), (4, 9);

-- Insertar relaciones rol-módulo-permiso
INSERT INTO core.rol_modulo_permiso (rol_id, modulo_id, permiso_id) VALUES 
    -- Super Administrador: todos los permisos
    (1, 1, 1), (1, 1, 2), (1, 1, 3), (1, 1, 4), (1, 1, 10),
    (1, 2, 5), (1, 2, 6), (1, 2, 7), (1, 2, 8),
    (1, 3, 9),
    -- Administrador: permisos limitados
    (2, 1, 1), (2, 1, 2), (2, 1, 3),
    (2, 2, 5), (2, 2, 6), (2, 2, 7),
    (2, 3, 9),
    -- Usuario Estándar: solo lectura
    (3, 1, 1), (3, 2, 5), (3, 3, 9),
    -- Solo Lectura: solo visualización
    (5, 1, 1), (5, 2, 5), (5, 3, 9);

-- Insertar usuarios de prueba
INSERT INTO core.usuario (username, password_hash, fecha_creacion, activo, fecha_actualizacion, contacto_id)
VALUES 
    ('admin', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', CURRENT_DATE, true, NULL, 1),
    ('maria.admin', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', CURRENT_DATE, true, NULL, 2),
    ('usuario.test', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', CURRENT_DATE, true, NULL, 3);

-- Insertar relaciones usuario-rol
INSERT INTO core.usuario_rol (usuario_id, rol_id) VALUES 
    (1, 1),  -- admin es Super Administrador
    (2, 2),  -- maria.admin es Administrador
    (3, 3);  -- usuario.test es Usuario Estándar

-- Insertar relaciones organización-contacto
INSERT INTO core.organizacion_contacto (contacto_id, organizacion_id) VALUES 
    (2, 1),  -- María González trabaja en Tech Solutions
    (3, 2);  -- Contacto de Proveedor XYZ pertenece a Proveedor XYZ

-- Mensaje de confirmación
DO $$
BEGIN
    RAISE NOTICE 'Datos iniciales insertados correctamente para ERP Core';
    RAISE NOTICE 'Usuarios creados: admin (Super Admin), maria.admin (Admin), usuario.test (Usuario)';
    RAISE NOTICE 'Password por defecto: "password" (hash BCrypt)';
END $$;
EOF

print_success "Archivo corregido creado: init-db/02-insert-corrected.sql"

echo ""
echo "==============================================================================="
print_info "🔧 Para aplicar las correcciones:"
echo ""
echo "1. 📁 Renombrar archivo actual:"
echo "   mv init-db/02-insert.sql init-db/02-insert-old.sql"
echo ""
echo "2. 📁 Usar archivo corregido:"
echo "   mv init-db/02-insert-corrected.sql init-db/02-insert.sql"
echo ""  
echo "3. 🔄 Resetear base de datos:"
echo "   ./reset-database.sh"
echo ""
echo "4. 🧪 Probar aplicación:"
echo "   npm start"
echo ""
echo "==============================================================================="
print_info "👤 Usuarios de prueba que se crearán:"
echo ""
echo "• admin / password (Super Administrador)"
echo "• maria.admin / password (Administrador)"  
echo "• usuario.test / password (Usuario Estándar)"
echo ""
echo "==============================================================================="