#!/bin/bash
# =============================================================================
# Script de validación del esquema de base de datos
# Compara el SQL con las entidades TypeORM
# =============================================================================

echo "🔍 Validando esquema de base de datos..."
echo "==============================================================================="

# Función para validar columnas de una tabla
validate_table_columns() {
    local table_name=$1
    local entity_file=$2
    
    echo "📋 Validando tabla: $table_name"
    
    if [ -f "$entity_file" ]; then
        echo "✅ Entidad encontrada: $entity_file"
        
        # Extraer nombres de columnas de la entidad
        echo "📄 Columnas en la entidad:"
        grep -E "@Column|@PrimaryGeneratedColumn|@PrimaryColumn" "$entity_file" | \
        grep -o "name: '[^']*'" | \
        sed "s/name: '/  - /" | sed "s/'$//"
        
        echo ""
    else
        echo "❌ Entidad no encontrada: $entity_file"
        echo ""
    fi
}

echo "🏗️  Validando estructura de tablas principales..."
echo ""

# Validar cada tabla principal
validate_table_columns "usuario" "src/infrastructure/database/entities/usuario.entity.ts"
validate_table_columns "contacto" "src/infrastructure/database/entities/contacto.entity.ts"
validate_table_columns "tipo_contacto" "src/infrastructure/database/entities/tipoContacto.entity.ts"
validate_table_columns "organizacion" "src/infrastructure/database/entities/organizacion.entity.ts"
validate_table_columns "permiso" "src/infrastructure/database/entities/permisos.entity.ts"
validate_table_columns "rol" "src/infrastructure/database/entities/rol.entity.ts"
validate_table_columns "modulo" "src/infrastructure/database/entities/modulo.entity.ts"
validate_table_columns "sistema" "src/infrastructure/database/entities/sistema.entity.ts"
validate_table_columns "cuenta_bancaria" "src/infrastructure/database/entities/cuentaBancaria.entity.ts"

echo "==============================================================================="
echo "🔗 Verificando relaciones many-to-many..."
echo ""

echo "📋 Tablas de relación esperadas:"
echo "  - usuario_rol"
echo "  - organizacion_contacto"
echo "  - organizacion_sistema"
echo "  - modulo_permiso"
echo "  - rol_modulo_permiso"

echo ""
echo "📋 Tablas de relación en SQL:"
grep -E "CREATE TABLE.*(" init-db/01-init.sql | grep -v "CREATE TABLE \"[a-z]*\"" | sed 's/CREATE TABLE "/  - /' | sed 's/" ($//'

echo ""
echo "==============================================================================="
echo "⚠️  Diferencias importantes encontradas:"
echo ""

echo "🔧 CORRECCIONES REALIZADAS:"
echo "  1. ✅ tipo_contacto_id: Agregado GENERATED BY DEFAULT AS IDENTITY"
echo "  2. ✅ organizacion_id: Agregado GENERATED BY DEFAULT AS IDENTITY" 
echo "  3. ✅ cuenta_id: Agregado GENERATED BY DEFAULT AS IDENTITY"
echo "  4. ✅ sistema_id: Agregado GENERATED BY DEFAULT AS IDENTITY"
echo "  5. ✅ modulo_id: Agregado GENERATED BY DEFAULT AS IDENTITY"
echo "  6. ✅ Columnas de permiso: Cambiadas a per_nombre, per_desc, per_cod, per_activo"
echo "  7. ✅ Longitudes de VARCHAR en contacto: Especificadas (50 caracteres)"

echo ""
echo "🚨 PENDIENTES DE VERIFICAR:"
echo "  1. ❓ Verificar si fecha_actualizacion debe ser nullable"
echo "  2. ❓ Confirmar tipos de datos para campos de texto vs varchar"
echo "  3. ❓ Validar restricciones de longitud en otros campos VARCHAR"

echo ""
echo "==============================================================================="
echo "🎯 RECOMENDACIONES:"
echo ""
echo "1. 🔄 Reiniciar la base de datos para aplicar cambios:"
echo "   ./reset-database.sh"
echo ""
echo "2. 🧪 Probar la aplicación:"
echo "   npm start"
echo ""
echo "3. 🐛 Si hay errores, revisar logs:"
echo "   docker compose logs postgres -f"
echo ""
echo "==============================================================================="